README.rst
As the title says, this fixes a typo found in the README.rst on line 107.
=> Fixes typo: teel -> tell

Portage/EBuild.hs
I'm not entirely across the change behind [Gentoo bug 666330](https://bugs.gentoo.org/666330), but I assume that it is worth updating HackPort to generate "Gentoo Authors" by default instead of "Gentoo Foundation", despite repoman automatically updating this before committing.
=> Update Gentoo Foundation to Gentoo Authors

Portage/GHCCore.hs
The changes build successfully, tested using `cabal build` locally.
The versions of the bundled libraries were determined from both the ghc tarball's `libraries/` directory, and the [GHC 8.6.1 Release Notes](https://downloads.haskell.org/~ghc/8.6.1/docs/html/users_guide/8.6.1-notes.html#included-libraries).
Signed-off-by: Jack Todaro <jackmtodaro@gmail.com>
=> Portage/GHCCore.hs: add libraries bundled with ghc-8.6.1

Merge.hs, Portage/Metadata.hs
I'm sure more could be done, but I'd like to open this PR for review and suggestions.
This patch changes the type signature and behaviour of `makeDefaultMetadata`
and `mergeEbuild` to accomodate the automatic generation of Cabal flags and
their descriptions in the metadata.xml.
The changes have been tested on two packages: one which has USE flags
(app-text/pandoc), and one which does not (dev-haskell/control-monad-free).
In both circumstances, the generated metadata.xml is correctly formatted.
Where the existing and new metadata.xml differ, the current behaviour of
HackPort remains the same, ie, the current metadata.xml will not be
overwritten.
In the case of a package with no USE flags, currently this patch still writes
the `<use>` and `</use>` tags, but leaves its contents empty.
Bug: …
=> Metadata: automatically generate flags for metadata.xml

Merge.hs, Portage/PackageId.hs
Opening for review and suggestions.
**Overview**
This teaches hackport to generate and display a diff between a newly-merged
version of a package and its most immediate previous version, if available.
This is not currently switchable. If there is no previous version available
such as when merging a new package, hackport will not call diff.
**Benefits**
The main benefit of this functionality is to allow the ebuild author to more
easily detect unintended changes between version bumps. A small diff is
likely to suggest no major changes, whereas a large diff should signal to
the ebuild author that further investigation may be necessary.
**Room for improvement**
- More use of parsers could be used to clean up the `filePathToPackageId` function
- Improve error handling and propagation by using …
=> Implement basic diff functionality

Merge.hs
Instead of packing `default_meta` directly into a `ByteString` (or the earlier discussed solution of using `Text`), this patch:
1. encodes to UTF-8 using `stringUtf8` from `Data.ByteString.Builder`; and
2. converts the resultant `Builder` into a lazy `ByteString`.
Everything else remains the same.
I decided on this method over using `Text` on the presumption that it may be more efficient. If you're happy with this implementation, I'll go ahead and push it.
=> Merge.hs: encode default_meta with UTF-8

Error.hs, Portage/Host.hs
Found a few kinks while getting started with hackport (as of 0.6 release).
Problem: The approach to grab `portage_dir` and `overlay_list` results in
`Nothing`, as they are no longer reported by `emerge --info`. There are error
messages that advise to set PORTDIR_OVERLAY in '/etc/make.conf'. Wrong file
location and obsolete variable. The message in (aptly named)
`showAnnoyingWarning` reflects missing information (my portage is in
'/var/portage' but it prints '/usr/portage'). This applies to `getInfo` using
emerge (no idea for paludis but the adjustments should not affect it).
Solution: Query `portageq` which is bundled with sys-apps/portage (instead of
parse-and-pray). Note that it does not have an advisable direct equivalent of
PORTDIR_OVERLAY, but provides the path to specific …
=> Portage/Host.hs: improved portage guess

Portage/GHCCore.hs
There are two very minor differences in built-in version list between ghc 8.6.3 and 8.6.5 (`process` and `transformers`), and in two cases I saw hackport bump the dependency to 8.8 (and cabal-3) because of that, even though it was good enough for 8.6.5. Therefore, adding this one and removing 8.6.1. Since we are at it, taking out one more (I think it's safe). More accurate and leaner at the same time.
If you think we should also drop 8.6.3 or keep 8.6.1 but drop 8.6.3, I don't have a strong opinion on that matter, you just let me know and I'll adjust accordingly.
Idea: Maybe take out from `GHCCore.hs` everything below 7.8.2? The lowest offered in overlay is 7.8.4 and that's a generous lower bound, as I have some doubts whether it would _actually work_ (I recently gave 7.10.3 a try and …
=> Portage/GHCCore.hs: add ghc-8.6.5

Cabal2Ebuild.hs, Main.hs, Merge.hs, Portage/Dependency/Print.hs, Portage/Overlay.hs, Portage/PackageId.hs, Portage/Resolve.hs, Portage/Use.hs, Portage/Version.hs, Status.hs
`Distribution.Text` and `Distribution.Compat.ReadP` are deprecated, and in Cabal-3 the former has its typeclass entirely removed and the latter is removed entirely (or, more accurately, moved to a `Deprecated` module).
To aid in the eventual migration to Cabal-3 inside hackport, I've hacked away at porting our use of `Distribution.Text` to mainly two, separate modules: `Distribution.Pretty` for pretty printing, and `Distribution.Parsec.Class` for parsing. I've also used `Distribution.Compat.CharParsing` for helpful character parsing functions that are seemingly a drop-in replacement for the `Distribution.Compat.ReadP` parsing functions.
I have noticed no regressions with simple `hackport merge x` commands so far.
While this PR is fine to be merged as-is provided the design and …
=> Port away from Distribution.Text and Distribution.Compat.ReadP

Cabal2Ebuild.hs, Main.hs, Merge/Dependencies.hs, Portage/Cabal.hs, Portage/GHCCore.hs, Portage/Overlay.hs, Portage/PackageId.hs, Portage/Version.hs, Status.hs, hackport.cabal
This pull request ports `hackport` to use Cabal-3 under the hood. All in all very few changes were needed to make it work, and it builds successfully on ghc-8.6.5. I _assume_ that it will continue to build on ghc-8.0.2 from skimming `Cabal.cabal` on hackage.
These changes could benefit from wider testing, which is why I propose that we push this to master for -9999 users to try out. If all goes well, we could cut a release.
@trofi , if you're happy with the changes I'll push to hackport and the cabal submodule all together.
=> Port to Cabal-3

.gitignore, Cabal2Ebuild.hs, Error.hs, HackPort/GlobalFlags.hs, Merge.hs, Merge/Dependencies.hs, Portage/Cabal.hs, Portage/Dependency/Types.hs, Portage/EBuild.hs, Portage/EBuild/CabalFeature.hs, Portage/EMeta.hs, Portage/GHCCore.hs, Portage/Metadata.hs, Portage/Overlay.hs, Portage/PackageId.hs, Portage/Tables.hs, Portage/Version.hs, hackport.cabal, tests/doctests.hs
The general gist of the new functionality is this:
1. If a new package version contains new USE flags, alphabetically insert them into the `metadata.xml`
2. If a new package version updates the description of an existing USE flag, overwrite the old description
3. Control (1) and (2) with a boolean flag (e.g. `--refresh-metadata`)
As it stands, (1) and (2) are complete and work as expected, thus this PR can be used for testing (note that commits will be squashed prior to the final merge). **(3) is outstanding**, so currently the functionality is hard enabled. This is partly because I wanted to first focus on getting that right before focusing on the switchable flag side of things, and partly because I'm completely unfamiliar with how we use `Cabal`'s argparser in `HackPort`.
This is a more …
=> Add --refresh-metadata functionality

Merge.hs, hackport.cabal
**Long story short:** run `pkgcheck` and `repoman` concurrently using `Control.Concurrent.forkIO` and `MVar`s.
**Long story:**
**EDIT:** the below commentary is superseded by [a newer comment](https://github.com/gentoo-haskell/hackport/pull/73#issuecomment-669054691).
The recent addition of `pkgcheck scan` slowed things down by about six seconds on my machine. Given a `hackport merge` can already take nearly a minute waiting for `repoman` to finish its checks, I don't want to make it even slower. 
Short of removing `pkgcheck` (which I'd rather not do due to its extra checks, and that it is the same tool running CI on `::gentoo` GitHub), and since we can't remove `repoman` either since `pkgcheck` doesn't implement all of its checks, the option is to run `pkgcheck` and `repoman` in …
=> Merge.hs: add concurrency where appropriate

Merge.hs, Merge/Utils.hs, tests/Merge/UtilsSpec.hs
Opening for review if anyone is interested, and to check the GitHub Actions CI against the various GHC versions. Assuming no issues I intend to push this change shortly.
This commit teaches hackport to recognise `USE_EXPAND`s and ignore their writing to the `metadata.xml`.
A summary of the changes:
**Merge.hs**
- `active_flag_descs_renamed` is simply `active_flag_descs` but with their `Cabal.flagName` replaced with any user-specified flag renames, if applicable.
- `iuse_flag_descs` is `active_flag_descs_renamed` with `USE_EXPAND`s stripped away.
**Merge/Utils.hs**
- Three functions have been added, one of which is exported for use in `Merge.hs` and another pure function exported to allow for testing via the test suite.
- `getUseExpands` returns a list of `USE_EXPAND`s currently found in …
=> Merge.hs: correctly handle USE_EXPANDs

hackport.cabal
This will make `hackport` use the maximum number of cores by default, instead of having to invoke `hackport +RTS -N -RTS ...`
See: https://downloads.haskell.org/ghc/latest/docs/html/users_guide/phases.html#ghc-flag--with-rtsopts=%E2%9F%A8opts%E2%9F%A9
=> hackport.cabal: Add default RTS flag

Portage/EBuild.hs
=> Portage/EBuild.hs: only add IUSE when it's not blank

Portage/EBuild.hs
I was unable to actually test this, because I'm not sure how to trigger this
section of the code generator.
It compiles, though, and the test suite passes.
=> Portage/Ebuild.hs: move S= to right after MY_P

Merge/Utils.hs, Portage/Metadata.hs, tests/Merge/UtilsSpec.hs, tests/Portage/MetadataSpec.hs
Currently, this is implemented without parsing `use.desc`. The reason for this is that I'm unsure if this will cause issues where a local USE flag, auto-generated from the package's cabal flag, has a different meaning to that of the global USE flag whose name it shares.
This PR also squashes any flag names with the word "debug" in it down to just "debug", so that it falls under the "debug" global USE flag.
Open to critique and discussion to improve, postpone or altogether abandon this change.
**Update 1**
This PR now also contains a rewrite of the `drop_prefix` function. See the commit message for details.
=> Teach hackport to handle global USE flags

Portage/EBuild.hs, tests/Portage/EBuildSpec.hs
Hello,
My personal site is HTTP-only, and is pointed to by a few packages (goatee* in the main tree, hoppy* and qtah* in my overlay).  May I please add my site to the HTTP blacklist so that the URL doesn't get rewritten to HTTPS?
Thanks.
=> Portage/EBuild.hs: add khumba.net to HTTP-only homepage list

src/Portage/EBuild.hs, tests/spec/Portage/EBuildSpec.hs
I've got with the times and have HTTPS on my site now.  Thanks for understanding before.
=> Portage.EBuild: Drop khumba.net from HTTP-only site list

src/Error.hs
Hackport won't compile with ghc-9.12 due to the addition of -Wderiving-typeable to -Wall
https://downloads.haskell.org/ghc/latest/docs/users_guide/9.12.1-notes.html#compiler
Anyhow, Typeable is automatically derived for all types since ghc-7.10
https://downloads.haskell.org/ghc/latest/docs/users_guide/using-warnings.html#ghc-flag-Wderiving-typeable
=> Error.hs: removing Typeable derivation
